In [ ]:
Data Preparation 


In [31]:
# Typical libraries used in Data Preparation

import numpy as np
import pandas as pd

In [32]:
#Using Series() for Series data construction. Note that Series uses pandas library
seriesdata = pd.Series([1, -3, 5, 20]) #Take note of the capital S since Python is case-sensitive
seriesdata

#Note that int64 means data types of values within 64-bit

0     1
1    -3
2     5
3    20
dtype: int64

In [33]:
#Comparison with list (using square bracket)
myseries = [1, -3, 5, 20]
myseries

[1, -3, 5, 20]

In [34]:
#Assigning the index on out own instead of pandas assigning it with initial '0'
#The syntax is pd.Series([],index = [])

seriesdata1 = pd.Series([1, -3, 5, 20], index = ['a', 'b', 'c', 'd'])
seriesdata

0     1
1    -3
2     5
3    20
dtype: int64

In [35]:
seriesdata1.values

array([ 1, -3,  5, 20])

In [36]:
seriesdata1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [37]:
seriesdata1[2]

5

In [38]:
seriesdata1[0:2]

a    1
b   -3
dtype: int64

In [39]:
seriesdata1['c']

5

In [41]:
seriesdata1['a':'c']

a    1
b   -3
c    5
dtype: int64

In [43]:
seriesdata1[['a','c']]

a    1
c    5
dtype: int64

In [45]:
seriesdata1[0] = 2
seriesdata1

seriesdata1['c'] = 6
seriesdata1

a     2
b    -3
c     6
d    20
dtype: int64

In [46]:
myarray = np.array([1, 2, 3, 4])
myarray

array([1, 2, 3, 4])

In [49]:
myarray = np.array([1, 2, 3, 4])
myarray

myseries2 = pd.Series(myarray)
myseries2

0    1
1    2
2    3
3    4
dtype: int64

In [51]:
myseries2[myseries2 > 3] #Remember that the inside of square bracket denotes labels or order. 

#In this case, we look for value larger than 3

3    4
dtype: int64

In [52]:
#Using logarithmic function with natural base e
#Documentation: https://numpy.org/doc/stable/reference/generated/numpy.log.html

np.log(myseries2)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
dtype: float64

In [57]:
mycolors = pd.Series([1,2,3,4,5,4,3,2], index = ['white', 'black', 'blue', 'green','yellow', 'green', 'blue', 'black'])
mycolors

white     1
black     2
blue      3
green     4
yellow    5
green     4
blue      3
black     2
dtype: int64

In [58]:
#Print out the unique values (no duplicates)
mycolors.unique()

array([1, 2, 3, 4, 5])

In [59]:
mycolors.value_counts

<bound method IndexOpsMixin.value_counts of white     1
black     2
blue      3
green     4
yellow    5
green     4
blue      3
black     2
dtype: int64>

In [65]:
#Determining if the values '5' and '7' are within the array entries

mycolors.isin([5,7])

white     False
black     False
blue      False
green     False
yellow     True
green     False
blue      False
black     False
dtype: bool

In [69]:
#Replacing the entries with Boolean value out of isin() command

mycolors[mycolors.isin([5,7])]

yellow    5
dtype: int64

In [72]:
mydict = {
    "white":10,
    "black":15,
    "red":30,
    "yellow":40
}

myseries3 = pd.Series(mydict)
myseries3

white     10
black     15
red       30
yellow    40
dtype: int64